/// All environment variables are declared here
#ifndef ENVIRONVARS_H
#define ENVIRONVARS_H
#include "SDL.h"

const int SCREEN_WIDTH = 1280;
const int SCREEN_HEIGHT = 720;

const int MAX_NUMKEYS = 20;

const int MAX_MAPSIZE_X = 70;  // number of tiles horizontal (REVERSED!!! actually vertical)
const int MAX_MAPSIZE_Y = 200;   // number of tiles vertical (REVERSED!!! actually horizontal)
const int MAX_TILE_LAYERS = 10;
const int MAX_TILE_TYPES = 150;

const int MAP_EMPTY_SPACE = 0;

const int INIT_JUMP_SPEED = 5;      // 5 default
const int INIT_JUMP_SPEED_ADJ = 5;
const int GRAVITY = 3;
const int JUMP_HEIGHT_HOLD_TIME = 180;  // milliseconds
const int Y_ACCEL_DELAY_MAX = 5;

const int MAX_X_SPEED = 6;
const int DEFAULT_X_SPEED = 3;
const int DEFAULT_X_ACCEL = 1;

const int MAX_FONTS = 10;

const double RADIANS = 0.01745329;

const int INVINCIBLE_LENGTH = 3000;

enum playerTextureNames { JIM_BASE_275, JIM_BASE_275_2, JIM_FUNNY_128, JIM_WHIPFLIP_500, JIM_LIGHTMAP };
enum HUDtextureNames { HUD_192 };
enum itemTextureNames { ITEMS_64, ITEMS_128 };
enum projectileTextureNames { PROJECTILES_40 };
enum effectTextureNames { EFFECTS_64, EFFECTS_128, EFFECTS_256 };
enum enemyTextureNames { ARCHER_LVL_1_128, ARCHER_LVL_2_128, ARCHER_LVL_3_128, CROW_LVL_1_128, SLIME_128, COOLAID_LVL_1_128, SPIDER_LVL_1_128 };
enum tileTypes { GROUND_TILE, LEFT_EDGE_TILE, RIGHT_EDGE_TILE };

enum staticText
{
    TUTORIAL, LEVEL_1, LEVEL_2, PAUSE, START_GAME, CONTROLS, OPTIONS, EXIT, LEVEL_3
};

enum HUDitems { BLUE_BAR, BLACK_BAR_BIG, EXTRA_LIFE, ORANGE_FADE, BLACK_BAR_SMALL, GREEN_BAR, RED_BAR, HUD_PART1, HUD_PART2 };
enum item128Status {  };
enum item64Status
{
    GUN1_PKUP, GUN2_PKUP, LIFE_PKUP, LIGHT_PKUP, HEALTH2_PKUP, HEALTH1_PKUP,
    WHIP_HOOK, TORCH, LEVER, CAGE_DOOR, WOOD_DOOR,
    QUESTION_SIGN, EXCLAMATION_SIGN, SKULL_SAVE_FLASH, SKULL_SAVE, LEVER_SHINE, CAGE_DOOR_SHINE
};
enum projectileStatus { ARROW_LVL_1, ARROW_LVL_2, ARROW_LVL_3, ARROW_LVL_3_MAGIC, SNOWMAN_FIREBALL, GREEN_SLIME, FIRE_STICKS, FIREBALL_FIRE_STICKS, SKULL };
enum effect64Status
{
    BIG_EXPL, RED_BUBBLE, SMOKE_EXPL, SMALL_FIREBALL, WATER_SPLASH, OVERHEAD_SMOKE, YELLOW_EXPL, ORANGE_EXPL, RED_EXPL, BLUE_EXPL, BLUE_SPIKE_BALL,
    PURPLE_STAR, SMALL_EXPL, CIRCLE_MAGIC, RED_STAR, WHIP_SNAP, BIG_SMOKE_EXPL,
    PLUS_5, GREEN_EXPL, PLUS_20, PLUS_10, PLUS_25, PLUS_50, PLUS_2, PLUS_100, PLUS_500, PLUS_250, PLUS_1, STAR_BURST, SAVE
};
enum effect128Status {  };
enum effect256Status { UPWARD_EXPL };

enum archerStatus { ARCHER_IDLE, ARCHER_ARROW_STRAIGHT, ARCHER_ARROW_ANGLE, ARCHER_HURT, ARCHER_ARROW_STRAIGHT_TRIPLE, ARCHER_ARROW_ANGLE_TRIPLE, ARCHER_DEAD };
enum crowStatus { CROW_IDLE, CROW_FLY, CROW_DIVE, CROW_HURT, CROW_DEAD };
enum slimeStatus { SLIME_IDLE, SLIME_HURT, SLIME_SPIN, SLIME_FALL, SLIME_DEAD };
enum coolAidStatus { COOLAID_IDLE, COOLAID_SHOOT, COOLAID_JUMP, COOLAID_HURT, COOLAID_DEAD };
enum spiderStatus { SPIDER_IDLE, SPIDER_WALK, SPIDER_ATTACK_1, SPIDER_ATTACK_2, SPIDER_HURT, SPIDER_DEAD };

enum playerNames { PLAYER_1, PLAYER_2 };
enum playerStatuses275
{
    IDLE, JUMP_UP, FALL_DOWN, LAND, WALK,
    WHIP_UP, WHIP_DOWN, WHIP_STAND, JUMP_WHIP,
    DUCK, STANDUP,
    SHOOT_STAND, SHOOT_STAND_RECOIL,
    SHOOT_UP, SHOOT_UP_RECOIL,
    SHOOT_DOWN, SHOOT_DOWN_RECOIL,
    SHOOT_DOWN_ANGLE, SHOOT_DOWN_ANGLE_RECOIL,
    SHOOT_UP_ANGLE, SHOOT_UP_ANGLE_RECOIL,
    CLIMB_EDGE, CLIMB, JUMP_FORWARD, HURT,
    JIM_BLOWUP, ROCKET_RIDE, FLEX_PANTS_DROP, GUN_FLIP,
    WHIP_FLIP
};

enum fontTypes
{
    CASQUE, CASQUE_30, BEN_GOTHIC, LAZY, COMICS_40, COMICS_150,
    BLOOD_150, CRACK_150, GRASS_150, JUNGLE_150, PINEWOOD_150, SKRATCHED_150, SNOT_150, VINES_150, WOODLOOK_150
};

enum cloudDepth { BACKGROUND, FOREGROUND };
enum layers { LAYER_0, LAYER_1, LAYER_2, LAYER_3, LAYER_4, LAYER_5, LAYER_6, LAYER_7, LAYER_8, LAYER_9 };
enum collDetectPoints { LOWER_MID, LOWER_LEFT, LOWER_RIGHT, CENTER, UPPER_MID, UPPER_RIGHT, UPPER_LEFT };
enum layerTypes { TILE_LAYER, ITEM_LAYER, CHARACTER_LAYER };
enum playerMovement { WORLD_SPACE, PIXELS_ONLY, WORLD_SPACE_AND_PIXELS };
enum direction { R, L };
enum keyValues { LCTRL, LALT, Z, UP, DOWN, RIGHT, LEFT, I, D, B, N, M, RETURN, SPACE };
enum keyStatusValues { NONE, PRESSED, RELEASED, LOCKED, AUTO_PRESSED };
enum horizStatusValues { STILL, MOVING };
enum verticalStatusValues { GROUND, JUMPING, FALLING, CLIMBING_EDGE, WHIP_FLIPING, CLIMBING_VINE };
enum keyProcessLvlValues { ALL_KEYS_ENABLED, ALL_KEYS_DISABLED, IN_AIR_KEYS_ONLY, LANDING_KEYS_ONLY, DEBUG_KEY, CLIMB_KEYS_ONLY };
enum animRepeatValues { REPEAT_ALL, REPEAT_LAST, NO_REPEAT, NO_REPEAT_KILL };
enum gameStatuses { GAME_INTRO, STORY_LINE, LEVEL_PLAYING, PAUSED, DEAD, GAME_OVER, LEVEL_COMPLETE, VIEW_CONTROLS, GAME_OPTIONS, LEVEL_INTRO };
#endif
